#!/home/samhaug/anaconda2/bin/python

import numpy as np
import obspy
from matplotlib import pyplot as plt
from os import listdir
import seispy

'''
Use this as a tool to compare as many synthetic sections as you want.
'''

home_dir = '/home/samhaug/work1/ScS_reverb_sims/mineos/FJ_v3.0_h6/'
include_list = [0,24,26,28,30]

def plot_section(st_list,name_list):

    fig,ax = plt.subplots(figsize=(10,15))

    for ist,st in enumerate(st_list):
        t = np.linspace(0,st[0].stats.npts,num=st[0].stats.npts)
        c = np.random.rand(3,1)
        for idx,tr in enumerate(st):
            if idx == 1:
                ax.plot(t,tr.data+idx,color=c,label=name_list[ist],alpha=0.5)
            else:
                ax.plot(t,tr.data+idx,color=c,alpha=0.5)
    ax.legend()
    plt.show()

def prep_station(st):

    st.filter('bandpass',freqmin=1/60.,freqmax=1/25.)
    st.interpolate(1)
    st = seispy.data.normalize_on_phase(st,phase=['ScSScS'])
    for idx,tr in enumerate(st):
        s = tr.stats.starttime
        e = tr.stats.endtime
        st[idx] = tr.slice(s+1800,s+4000)
    st.integrate().normalize()
    return st

stream_dir = listdir(home_dir)

stream_list = []
for ii in stream_dir:
    if int(ii.split('_')[-1][1::]) in include_list:
        stream_list.append(ii)

st_list = []
for ii in stream_list:
    st = obspy.read(home_dir+ii+'/st_T.pk')
    st = prep_station(st)
    st_list.append(st)

print st_list
print stream_list
plot_section(st_list,stream_list)


