#!/home/samhaug/anaconda2/bin/python

import numpy as np
from mpl_toolkits.basemap import Basemap, cm
import matplotlib.pyplot as plt
import obspy
import glob
from subprocess import call

'''
Plots a mapview of all china stations. It references a folder with
pk files that have been sorted into their networks
Change directory by changing pk_file
'''

pk_file = '/home/samhaug/work1/ScS_reverb_data/20160130/*.pk'


fig,ax = plt.subplots(figsize=(18,18))
#ax = fig.add_axes([0.1,0.1,0.8,0.8])

m = Basemap(width=7000000,height=4500000,
            resolution='l',projection='aea',\
            lat_1=25.,lat_2=43,lon_0=113,lat_0=34)

m.drawcoastlines()
#m.fillcontinents(color='gray',lake_color='white',alpha=0.5)
#m.drawstates()
m.drawcountries()

for idx,ii in enumerate(glob.glob(pk_file)):
    print str(idx)+'/'+str(len(glob.glob(pk_file)))
    st = obspy.read(ii)
    lons = []
    lats = []
    for tr in st:
        lons.append(tr.stats.sac['stlo'])
        lats.append(tr.stats.sac['stla'])
    x,y = m(lons,lats)
    net = st[0].stats.network
    m.scatter(x,y,5,marker='o',color=np.random.rand(3,1),label=net)
plt.legend(ncol=4,loc=4)

plt.savefig('plot_china_stations.pdf')
call('evince plot_china_stations.pdf',shell=True)
