#!/home/samhaug/anaconda2/bin/python

import obspy
import numpy as np
import seispy
from scipy.signal import tukey
from obspy.taup import TauPyModel
from matplotlib import pyplot as plt
from os import listdir
from scipy.signal import correlate
from matplotlib import pylab as p

'''
Use this script as a tool for checking what source depth best explains
depth phase separation.

Use this to examine ScS_n+1 - ScS_n travel times as a function of source
depth.

Drag and drop to align on ScS_2. See how well the depth phase
separation matches.

'''

def main():
    '''
    Change data and simulation here.
    '''
    sim_dir = '/home/samhaug/work1/ScS_reverb_sims/mineos/japan_v9.0/'
    data_dir = '/home/samhaug/work1/ScS_reverb_data/081412_japan/'
    std = setup_data(data_dir)
    fig,ax_list = plt.subplots(1,6,figsize=(20,30))

    include_list = ('h0','h10','h-10','h-20','h20')
    sim_dir_list = listdir(sim_dir)
    sim_list = [i for i in sim_dir_list if i.endswith(include_list)]
    print sim_list

    for idx,dir in enumerate(sim_list):
        sts = setup_sim(sim_dir+dir+'/')
        compare_plot(sts,std,ax_list[idx],dir)

    dragh = DragHandler()
    plt.tight_layout()
    plt.show()

def remove_list(include_list,sim_dir):
    o_sim_list = listdir(sim_dir)
    print o_sim_list
    o_sim_list.sort()
    sim_list = []
    for ii in o_sim_list:
        if float(ii.split('_')[-1]) in include_list:
            sim_list.append(ii)
    return sim_list

def setup_data(data_dir):
    st = obspy.read(data_dir+'st_T.pk')
    st.integrate().detrend()
    st.interpolate(1)
    st.filter('bandpass',freqmin=1/80.,freqmax=1/10.,zerophase=True)
    st.sort(['station'])
    st = seispy.filter.range_filter(st,(10,90))
    #for idx,tr in enumerate(st):
    #    st[idx] = seispy.data.phase_window(tr,phase=['ScSScS'],window=(-400,2200))
    return st

def setup_sim(sim_dir):
    st = obspy.read(sim_dir+'st_T.pk')
    st.integrate().detrend().integrate().detrend()
    st.interpolate(1)
    st.filter('bandpass',freqmin=1/80.,freqmax=1/10.,zerophase=True)
    st.sort(['station'])
    st = seispy.filter.range_filter(st,(10,90))
    #for idx,tr in enumerate(st):
    #    st[idx] = seispy.data.phase_window(tr,phase=['ScSScS'],window=(-400,2200))
    return st

def compare_plot(sts,std,ax,title):
    for idx,tr in enumerate(std):
        ax.tick_params(axis='both', which='major', labelsize=3)
        ax.set_ylim(-1,len(sts))
        ax.set_title(str(sts[idx].stats.sac['evdp'])+'_'+title,size=7)
        ax.grid()

        trs1 = seispy.data.phase_window(sts[idx],['ScSScS'],window=(-50,250))
        trs1.normalize()

        trd1 = seispy.data.phase_window(std[idx],['ScSScS'],window=(-50,250))
        trd1.normalize()

        iroll = 100-np.argmax(trs1.data)
        trs1.data = np.roll(trs1.data,iroll)

        ax.plot(idx+trd1.data/2.,alpha=0.7,color='k')
        ax.plot(idx+trs1.data/2.,alpha=0.7,color='r',
                picker=True,label='sim',pickradius=15)

class DragHandler(object):
    """ A simple class to handle Drag n Drop.

    This is a simple example, which works for Text objects only.
    """
    def __init__(self, figure=None) :
        """ Create a new drag handler and connect it to the figure's event system.
        If the figure handler is not given, the current figure is used instead
        """
        if figure is None : figure = p.gcf()
        # simple attibute to store the dragged text object
        self.dragged = None

        # Connect events and callbacks
        figure.canvas.mpl_connect("pick_event", self.on_pick_event)
        figure.canvas.mpl_connect("button_release_event", self.on_release_event)

    def on_pick_event(self, event):
        " Store which text object was picked and were the pick event occurs."

        if event.artist.get_label() == 'sim':
            self.dragged = event.artist
            self.xdata = event.artist.get_data()[0]
            self.ydata = event.artist.get_data()[1]
            self.pick_pos = event.mouseevent.xdata
        return True

    def on_release_event(self, event):
        " Update text position and redraw"

        if self.dragged is not None :
            newx = event.xdata
            newy = np.roll(self.ydata,int(newx-self.pick_pos))
            self.dragged.set_data(self.xdata,newy)
            self.dragged = None
            p.draw()
        return True

main()






