#!/home/samhaug/anaconda2/bin/python

import obspy
import numpy as np
import seispy
from scipy.signal import tukey
from obspy.taup import TauPyModel
from matplotlib import pyplot as plt
from os import listdir
from scipy.signal import correlate

'''
Very similar to mask_ScS. This script is used to verify if a perturbed
depth/PREM model works.

Use this to examine ScS_n+1 - ScS_n travel times.
'''

model = TauPyModel(model='prem')
model_sim = TauPyModel(model='prem_p2.5')


sim_dir = '/home/samhaug/work1/ScS_reverb_sims/mineos/220_tar/depth_pert'
data_dir = '/home/samhaug/work1/ScS_reverb_data/20160130/'

st_data = obspy.read(data_dir+'FJ_clean.pk')
st_data.sort(['station'])

st = obspy.read(sim_dir+'/st_T.pk')
st.sort(['station'])

st_data.filter('bandpass',freqmax=1/25.,freqmin=1/60.)
st_data = seispy.data.normalize_on_envelope(st_data)
st_data = seispy.data.align_on_phase(st_data,phase=['ScSScS'],a_min=False)

st.filter('bandpass',freqmax=1/25.,freqmin=1/60.)
st.interpolate(1)
st.integrate()
st.normalize()
st = seispy.data.normalize_on_envelope(st)
st = seispy.data.align_on_phase(st,phase=['ScSScS'],a_min=False,model='prem_p2.5')

print len(st_data)
print len(st)
for idx, tr in enumerate(st):
    fig,ax = plt.subplots()
    tr_synth = seispy.data.phase_window(st[idx],['ScSScS'],window=(-10,2050))
    ax.plot(np.roll(tr_synth.data,-2),alpha=0.4)
    tr_data = seispy.data.phase_window(st_data[idx],['ScSScS'],window=(-10,2050))
    tr_data.interpolate(1)
    ax.plot(tr_data.data,alpha=0.4,color='k')

    plt.show()
