#!/home/samhaug/anaconda2/bin/python

import obspy
import numpy as np
import seispy
import scipy
from scipy.signal import tukey
from obspy.taup import TauPyModel
from matplotlib import pyplot as plt
from os import listdir
from scipy.signal import correlate
from matplotlib import pylab as p

'''
This is a general tool for comparing seismograms from perturbed models to
data. The simulation directories must be delimited by underscores. The second
group of strings is a number that is checked for. This script plots data traces
stacked on max correlation.
'''

def main():
    ### Change data and simulation here.
    sim_dir = '/home/samhaug/work1/ScS_reverb_sims/mineos/japan_v9.0/'
    data_dir = '/home/samhaug/work1/ScS_reverb_data/081412_japan/'

    run = 'japan_9.0_h10/'


    std = setup_data(data_dir)
    sts = setup_sim(sim_dir+run)
    for idx, tr in enumerate(std):
        sts[idx].stats.starttime = tr.stats.starttime

    seispy.plot.compare_section(std,sts)
    plt.tight_layout()
    plt.show()

def setup_data(data_dir):
    st = obspy.read(data_dir+'st_T.pk')
    st.integrate().detrend()
    st.interpolate(1)
    st.filter('bandpass',freqmin=1/80.,freqmax=1/15.,zerophase=True)
    st.sort(['station'])
    st = seispy.data.align_on_phase(st,phase=['ScSScS'])
    st = seispy.filter.range_filter(st,(10,90))
    for idx,tr in enumerate(st):
        st[idx] = seispy.data.phase_window(tr,phase=['ScSScS'],window=(-400,2200))
    st.normalize()
    return st

def setup_sim(sim_dir):
    st = obspy.read(sim_dir+'st_T.pk')
    st.integrate().detrend().integrate().detrend()
    st.interpolate(1)
    st.filter('bandpass',freqmin=1/80.,freqmax=1/15.,zerophase=True)
    st.sort(['station'])
    st = seispy.data.align_on_phase(st,phase=['ScSScS'])
    st = seispy.filter.range_filter(st,(10,90))
    for idx,tr in enumerate(st):
        st[idx] = seispy.data.phase_window(tr,phase=['ScSScS'],window=(-400,2200))
    st.normalize()
    return st

main()




